Repository codestates-seb/seb41_main_004, pull requests merged in 2023-01, with the labels that each got.

#2 [# 이슈번호]통신테스트 변수 변경
  azit-back/src/main/java/com/codestates/azitserver/HealthCheckController.java
Labels: feat, Backend

#3 [#이슈번호] 통신테스트 변수 변경2
  .gitignore
  azit-back/src/main/java/com/codestates/azitserver/HealthCheckController.java
Labels: feat, Backend

#23 [common] 도메인 공통기능 구현
  .github/workflows/gradle-server-deploy.yml
  .github/workflows/gradle-server-test.yml
  .github/workflows/gradle-server.yml
  azit-back/.gitignore
  azit-back/src/main/java/com/codestates/azitserver/AzitServerApplication.java
  azit-back/src/main/java/com/codestates/azitserver/domain/common/BaseEntity.java
  azit-back/src/main/java/com/codestates/azitserver/domain/common/CustomBeanUtils.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/WebMvcConfig.java
  azit-back/src/main/java/com/codestates/azitserver/global/dto/MultiResponseDto.java
  azit-back/src/main/java/com/codestates/azitserver/global/dto/PageInfo.java
  azit-back/src/main/java/com/codestates/azitserver/global/dto/SingleResponseDto.java
Labels: feat, Backend

#27 [Hotfix] env.properties와 Auditable.java 문제 수정
  .github/workflows/gradle-server-test.yml
  azit-back/src/main/java/com/codestates/azitserver/AzitServerApplication.java
  azit-back/src/main/java/com/codestates/azitserver/domain/common/Auditable.java
  azit-back/src/main/java/com/codestates/azitserver/domain/common/BaseEntity.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/Member.java
  azit-back/src/main/java/com/codestates/azitserver/domain/review/entity/review.java
  azit-back/src/main/resources/env.properties
Labels: fix, bug

#30 chore: Login / Signup page 부분 구현
  azit-front/package-lock.json
  azit-front/src/App.js
  azit-front/src/components/Button.js
  azit-front/src/components/LoginComponent/Button.js
  azit-front/src/images/basicProfileImgIcon.png
  azit-front/src/images/google-login.png
  azit-front/src/images/imgAddIcon.png
  azit-front/src/images/kakao-login.png
  azit-front/src/images/logo.png
  azit-front/src/pages/Login.js
  azit-front/src/pages/Signup.js
  azit-front/src/pages/SignupAdditional.js
Labels: chore, Frontend

#31 Chore/azitcreatepage
  azit-front/package-lock.json
  azit-front/src/App.js
  azit-front/src/GlobalStyle.js
  azit-front/src/components/AzitCreate/AzitcreateForm.js
  azit-front/src/images/BannerImg.png
  azit-front/src/pages/Azitcreate.js
Labels: chore, Frontend

#34 Chore/azitcreatepage
  azit-front/src/components/AzitCreate/AzitcreateForm.js
Labels: chore, Frontend

#37 AzitSettingPage markup 완료
  azit-front/src/App.js
  azit-front/src/components/Gnb.js
  azit-front/src/images/AzitSettingBarArrow.png
  azit-front/src/pages/AzitSetting.js
Labels: Frontend

#40 chore: Login / Signup page Mark Up
  azit-front/src/components/LoginComponent/Button.js
  azit-front/src/pages/FindPassword.js
  azit-front/src/pages/SignupAdditional.js
Labels: chore, Frontend

#41 add AzitEditPage & edit button component, AzitCreatePage
  azit-front/src/App.js
  azit-front/src/components/AzitCreate/AzitcreateForm.js
  azit-front/src/components/AzitEdit/AzitEditForm.js
  azit-front/src/components/Button.js
  azit-front/src/pages/AzitEdit.js
Labels: Frontend

#44 chore: Loading page Markup
  azit-front/src/images/logoWhite.png
  azit-front/src/pages/Loading.js
Labels: chore, Frontend

#45 AzitJoin markup
  azit-front/src/App.js
  azit-front/src/pages/AzitJoin.js
Labels: Frontend

#51 [Chore] AzitReportPage 마크업 작업 완료 & select css 수정 & GlobalStyle 수정
  azit-front/src/App.js
  azit-front/src/GlobalStyle.js
  azit-front/src/components/AzitCreate/AzitcreateForm.js
  azit-front/src/components/AzitEdit/AzitEditForm.js
  azit-front/src/pages/AzitEdit.js
  azit-front/src/pages/AzitReport.js
Labels: Frontend

#53 [chore] Login / Signup page 라우팅 구조 구현
  azit-front/src/App.js
  azit-front/src/pages/Loading.js
  azit-front/src/pages/Login.js
  azit-front/src/pages/Signup.js
  azit-front/src/pages/SignupAdditional.js
Labels: chore, Frontend

#57 edit-icon 변경
  azit-front/src/images/edit-icon.png
Labels: Frontend

#56 [club] 아지트 CRUD 구현 - 클럽 정보 수정 및 예약 취소 기능 구현
  azit-back/src/docs/asciidoc/index.adoc
  azit-back/src/main/java/com/codestates/azitserver/domain/club/controller/ClubController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/mapper/ClubMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubService.java
  azit-back/src/main/java/com/codestates/azitserver/global/validator/NotSpace.java
  azit-back/src/main/java/com/codestates/azitserver/global/validator/NotSpaceValidator.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubControllerTestHelper.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/ClubStubData.java
  azit-back/src/test/java/com/codestates/azitserver/global/utils/ControllerTestHelper.java
Labels: feat, test, Backend

#60 [chore] UserProfileEdit page Markup
  azit-front/src/App.js
  azit-front/src/components/LoginComponent/Button.js
  azit-front/src/pages/Login.js
  azit-front/src/pages/UserProfileEdit.js
Labels: chore, Frontend

#62 [chore] UserResetPassword page Markup
  azit-front/src/App.js
  azit-front/src/pages/UserResetPassword.js
Labels: chore, Frontend

#67 페이지 버튼 수정 및 신고 아이콘 추가
  azit-front/src/App.js
  azit-front/src/components/AzitCreate/AzitcreateForm.js
  azit-front/src/components/AzitEdit/AzitEditForm.js
  azit-front/src/components/Button.js
  azit-front/src/images/reportIcon.png
  azit-front/src/pages/AzitEdit.js
  azit-front/src/pages/AzitJoin.js
  azit-front/src/pages/AzitReport.js
Labels: Frontend

#47 [auth] 일반 회원 로그인 인증 구현
  azit-back/build.gradle
  azit-back/src/docs/asciidoc/index.adoc
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/dto/LoginDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/filter/JwtAuthenticationFilter.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/filter/JwtVerificationFilter.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/handler/MemberAccessDeniedHandler.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/handler/MemberAuthenticationEntryPoint.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/handler/MemberAuthenticationFailureHandler.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/handler/MemberAuthenticationSuccessHandler.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/jwt/JwtTokenizer.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/userdetails/MemberDetailsService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/utils/CustomAuthorityUtils.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/utils/ErrorResponder.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/Member.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/repository/MemberRepository.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/EmbeddedRedisConfig.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/RedisConfig.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/main/resources/application.yml
  azit-back/src/test/java/com/codestates/azitserver/domain/auth/JwtTokenizerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/auth/authLoginTest.java
Labels: feat, test, Backend

#70 Gnb 링크 수정 & AzitDetailPage Markup
  azit-front/src/App.js
  azit-front/src/components/AzitDetailHeader.js
  azit-front/src/components/Gnb.js
  azit-front/src/images/AzitExampleImg.png
  azit-front/src/pages/AzitDetail.js
Labels: Frontend

#71 App.js 오타 수정
  azit-front/src/App.js
Labels: Frontend

#73 Chore/user report 페이지 마크업
  azit-front/src/App.js
  azit-front/src/components/FollowCheck/FollowList.js
  azit-front/src/components/FollowCheck/FollowTab.js
  azit-front/src/components/FollowCheck/FollowingList.js
  azit-front/src/components/MyPage/Profile.js
  azit-front/src/pages/UserReport.js
Labels: chore, Frontend

#75 AzitDetail.js,AzitPreview.js 마진 수정
  azit-front/src/pages/AzitDetail.js
  azit-front/src/pages/AzitPreview.js
Labels: Frontend

#77 [chore] Modal 컴포넌트 구현
  azit-front/src/App.js
  azit-front/src/components/Modal.js
  azit-front/src/images/closeIcon.png
  azit-front/src/images/imgIcon.png
  azit-front/src/pages/SignupAdditional.js
  azit-front/src/pages/UserProfileEdit.js
Labels: chore, Frontend

#79 [auth] Redis 충돌 해결 시도
  azit-back/src/main/java/com/codestates/azitserver/AzitServerApplication.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/EmbeddedRedisConfig.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/RedisConfig.java
  azit-back/src/main/resources/application.yml
  azit-back/src/test/java/com/codestates/azitserver/domain/auth/authLoginTest.java
  azit-back/src/test/resources/application-test.yml
Labels: fix, Backend

#82 Azitcreatepage Img Modal 추가
  azit-front/src/pages/Azitcreate.js
Labels: Frontend

#83 App.js 반복 사용된 라우트 제거
  azit-front/src/App.js
Labels: Frontend

#84 location Modal 추가
  azit-front/src/components/AzitCreate/AzitcreateForm.js
Labels: Frontend

#90 [Club/Get] 아지트 조회 부분 구현
  azit-back/build.gradle
  azit-back/src/main/java/com/codestates/azitserver/domain/category/controller/CategoryController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/category/entity/CategorySmall.java
  azit-back/src/main/java/com/codestates/azitserver/domain/category/mapper/CategoryMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/controller/ClubController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/entity/Club.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/mapper/ClubMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/repository/ClubRepository.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubService.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/P6SpySqlFormatter.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/advice/GlobalExceptionAdvice.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ErrorResponse.java
  azit-back/src/main/resources/application-local.yml
  azit-back/src/test/java/com/codestates/azitserver/domain/category/controller/CategoryControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/ClubStubData.java
  azit-back/src/test/java/com/codestates/azitserver/global/config/EnableQueryLog.java
  azit-back/src/test/java/com/codestates/azitserver/global/config/P6SpySqlFormatterTest.java
Labels: feat, Backend

#91 [Club/Test] 아지트 조회 관련 테스트 코드 작성
  azit-back/src/docs/asciidoc/index.adoc
  azit-back/src/test/java/com/codestates/azitserver/domain/category/controller/CategoryControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/ClubStubData.java
  azit-back/src/test/java/com/codestates/azitserver/global/utils/ControllerTestHelper.java
Labels: test, Backend

#92 Gnb 수정 & 파일 이름수정
  azit-front/src/components/AzitCreate/AzitCreateForm.js
  azit-front/src/components/common/Gnb.js
  azit-front/src/pages/AzitCreate.js
Labels: Frontend

#93 Chore/my page 활동내역 수정
  azit-front/src/components/MyPage/ActivityHistory.js
Labels: Frontend

#98 관심사 카테고리 구현
  azit-front/src/pages/SignupAdditional.js
Labels: Frontend

#99 관심사 카테고리 색상 추가
  azit-front/src/pages/SignupAdditional.js
Labels: Frontend

#96 [Club/image]
  azit-back/src/docs/asciidoc/index.adoc
  azit-back/src/main/java/com/codestates/azitserver/domain/club/controller/ClubController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubService.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/global/utils/ControllerTestHelper.java
Labels: fix, Backend

#105 [chore] LoginRequestModal 구현
  azit-front/src/components/common/Modal.js
Labels: chore, Frontend

#115 feat: azitCreate 기능 구현
  azit-front/package-lock.json
  azit-front/package.json
  azit-front/src/components/AzitCreate/AzitCreateForm.js
  azit-front/src/pages/AzitCreate.js
  azit-front/src/pages/AzitDetail.js
Labels: feat, Frontend

#116 [feat] 일반 로그인 기능 부분 구현
  azit-front/package-lock.json
  azit-front/package.json
  azit-front/src/pages/Login.js
  azit-front/src/pages/Signup.js
  azit-front/src/pages/SignupAdditional.js
  azit-front/src/redux/loginSlice.js
  azit-front/src/redux/store.js
  azit-front/src/redux/userSlice.js
  azit-front/src/util/cookie/cookie.js
Labels: feat, Frontend

#112 [auth] 소셜 로그인 구현
  azit-back/build.gradle
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/dto/LoginResponseDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/filter/JwtAuthenticationFilter.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/filter/JwtVerificationFilter.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/handler/OAuthSuccessHandler.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/userdetails/MemberDetails.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/userdetails/MemberDetailsService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/utils/RedisUtils.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/Member.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/RedisConfig.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ErrorResponse.java
  azit-back/src/main/resources/application.yml
  azit-back/src/test/java/com/codestates/azitserver/domain/auth/authLoginTest.java
  azit-back/src/test/java/com/codestates/azitserver/global/exception/controller/ExceptionRestControllerTest.java
Labels: feat, Backend

#118 feat:검색 api 연결 및 env baseurl 설정
  azit-front/.env
  azit-front/package-lock.json
  azit-front/package.json
  azit-front/src/pages/Search.js
Labels: feat, Frontend

#117 [Auth/Loginuser] api 요청시 요청 주체를 확인하는 코드 구현
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/filter/JwtVerificationFilter.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/controller/ClubController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/controller/ClubMemberController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubMemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/entity/Club.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/entity/ClubMember.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/entity/ClubReport.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/mapper/ClubMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/mapper/ClubMemberMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/repository/ClubMemberRepository.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubMemberService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/common/Report.java
  azit-back/src/main/java/com/codestates/azitserver/global/annotation/LoginMember.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ExceptionCode.java
  azit-back/src/main/resources/data.sql
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/ClubStubData.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/MemberStubData.java
Labels: refact, Backend

#119 feat: 소분류 카테고리 구현
  azit-front/src/components/AzitCreate/AzitCreateForm.js
Labels: feat, Frontend

#121 Feat/search
  azit-front/src/App.js
  azit-front/src/components/common/AzitList.js
  azit-front/src/dummyData/ClubData.js
  azit-front/src/pages/Search.js
  azit-front/src/util/toDateFormatOfKR.js
Labels: feat, Frontend

#128 feat: 주소 검색 기능 구현
  azit-front/src/components/AzitCreate/AzitCreateForm.js
  azit-front/src/pages/AzitCreate.js
Labels: feat, Frontend

#131 [Feat] 미리보기 페이지로 링크 연결
  azit-front/package-lock.json
  azit-front/package.json
  azit-front/src/components/AzitCreate/AzitCreateForm.js
Labels: feat, Frontend

#132 Feat/profile 프로필수정 기능 구현중
  azit-front/package-lock.json
  azit-front/package.json
  azit-front/src/App.js
  azit-front/src/components/AzitCreate/AzitCreateForm.js
  azit-front/src/components/MyPage/ActivityHistory.js
  azit-front/src/components/MyPage/Profile.js
  azit-front/src/components/MyPage/Reviews.js
  azit-front/src/components/MyPage/UserPageHeader.js
  azit-front/src/components/common/AzitList.js
  azit-front/src/index.js
  azit-front/src/pages/UserProfileEdit.js
  azit-front/src/redux/store.js
  azit-front/src/redux/userProfileSlice.js
Labels: feat, Frontend

#134 [feat] 일반 로그인 기능 부분 구현
  azit-front/package-lock.json
  azit-front/package.json
  azit-front/src/pages/Login.js
  azit-front/src/pages/Signup.js
  azit-front/src/pages/SignupAdditional.js
Labels: feat, Frontend

#135 [Feat] azitSlice 추가
  azit-front/src/components/AzitCreate/AzitCreateForm.js
  azit-front/src/redux/azitSlice.js
  azit-front/src/redux/store.js
Labels: feat, Frontend

#136 Feat/search
  azit-front/package-lock.json
  azit-front/package.json
  azit-front/src/components/common/AzitList.js
  azit-front/src/dummyData/ClubData.js
  azit-front/src/index.js
  azit-front/src/pages/Search.js
  azit-front/src/util/axios.js
  azit-front/src/util/toDateFormatOfKR.js
Labels: feat, Frontend

#137 feat:로딩 컴포넌트 추가 및 react query 기본 구조 추가
  azit-front/src/components/common/Loading.js
  azit-front/src/images/loading.gif
  azit-front/src/pages/Search.js
Labels: feat, Frontend

#139 [feat] 로그인 에러핸들링 및 로그아웃 기능 구현
  azit-front/package-lock.json
  azit-front/src/components/Logout/LogoutRequestModal.js
  azit-front/src/pages/Login.js
  azit-front/src/pages/Signup.js
  azit-front/src/pages/UserPageSetting.js
Labels: feat, Frontend

#140 Feat/search
  azit-front/package-lock.json
  azit-front/package.json
  azit-front/src/components/Search/Defalut.js
  azit-front/src/pages/Search.js
Labels: feat, Frontend

#141 [Feat] AzitPreview 구현 및 필요한 함수 추가
  azit-front/src/components/AzitCreate/AzitCreateForm.js
  azit-front/src/pages/AzitCreate.js
  azit-front/src/pages/AzitDetail.js
  azit-front/src/pages/AzitPreview.js
  azit-front/src/util/azitPreviewDateConvert.js
Labels: feat, Frontend

#143 [member] 회원 엔티티에 관심사 추가, member post에 관심사 포함하도록 api 문서 테스트 수정
  azit-back/src/main/java/com/codestates/azitserver/domain/category/entity/CategorySmall.java
  azit-back/src/main/java/com/codestates/azitserver/domain/category/repository/CategorySmallRepository.java
  azit-back/src/main/java/com/codestates/azitserver/domain/category/service/CategoryService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/dto/MemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/Member.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/MemberCategory.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberService.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/MemberStubData.java
Labels: docs, feat, Backend

#133 [hotfix/club] 아지트 배너 이미지 더미 데이터 및 api 명세서
  azit-back/src/main/resources/data.sql
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubFieldDescriptor.java
Labels: fix, Backend

#146 [Feat/auth] 비밀번호 인증, 변경 기능 구현
  azit-back/src/docs/asciidoc/index.adoc
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/controller/AuthController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/dto/LoginDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/dto/LoginResponseDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/filter/JwtAuthenticationFilter.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/handler/OAuthSuccessHandler.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/service/AuthService.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/test/java/com/codestates/azitserver/domain/auth/authControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/auth/authLoginTest.java
Labels: feat, test, Backend

#163 [feat] 아지트 생성 기능 구현(통신)
  azit-front/package-lock.json
  azit-front/src/components/AzitCreate/AzitCreateForm.js
  azit-front/src/pages/AzitPreview.js
  azit-front/src/util/azitPreviewDateConvert.js
Labels: feat, Frontend

#160 Hotfix/club
  azit-back/src/main/java/com/codestates/azitserver/domain/club/controller/ClubController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/entity/Club.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubService.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubControllerTest.java
Labels: refact, Backend

#168 [fix]아지트 생성 페이지 내 이미지 첨부 방식 수정
  azit-front/src/pages/AzitCreate.js
Labels: fix, Frontend

#152 [hotfix/auth] 로그인 이미지 null 에러
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/filter/JwtAuthenticationFilter.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/handler/OAuthSuccessHandler.java
Labels: fix, Backend

#171 [fix]아지트 미리보기 페이지 및 아지트 상세 페이지 마크업 수정/ 아지트 생성 페이지 코드 수정
  azit-front/src/components/AzitCreate/AzitCreateForm.js
  azit-front/src/pages/AzitDetail.js
  azit-front/src/pages/AzitPreview.js
Labels: fix, Frontend

#173 [fix] minYear 선택에 따른 maxYear 선택지 제한 걸기 추가
  azit-front/src/components/AzitCreate/AzitCreateForm.js
  azit-front/src/pages/AzitDetail.js
  azit-front/src/pages/AzitPreview.js
Labels: fix, Frontend

#174 Feat/main page
  azit-front/.env
  azit-front/src/components/AzitCreate/AzitCreateForm.js
  azit-front/src/components/Home/CategoryPicker.js
  azit-front/src/components/Home/CategoryTab.js
  azit-front/src/components/Home/DatePicker.js
  azit-front/src/components/Home/DateTab.js
  azit-front/src/components/Home/Null.js
  azit-front/src/components/common/AzitList.js
  azit-front/src/pages/Search.js
  azit-front/src/util/toDateFormatOfKR.js
Labels: feat, Frontend

#176 [member] 관심사 적용된 api doc 완성
  azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/dto/MemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/Member.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/repository/MemberCategoryRepository.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberCategoryService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberService.java
  azit-back/src/main/resources/data.sql
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/MemberStubData.java
Labels: docs, feat, Backend

#178 [Feat] 아지트 개별 상세 페이지 기능 구현
  azit-front/src/components/AzitCreate/AzitCreateForm.js
  azit-front/src/components/AzitDetail/AzitDetailHeader.js
  azit-front/src/pages/AzitDetail.js
  azit-front/src/pages/AzitPreview.js
Labels: feat, Frontend

#170 [Hotfix] 아지트 주소 필드 저장 길이, 파일 업로드시 확장자 확인
  azit-back/src/main/java/com/codestates/azitserver/domain/club/entity/Club.java
  azit-back/src/main/java/com/codestates/azitserver/domain/fileInfo/service/StorageService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/fileInfo/service/StorageServiceAwsS3.java
  azit-back/src/main/java/com/codestates/azitserver/domain/fileInfo/service/StorageServiceLocal.java
Labels: fix, Backend

#179 [member] patch에서 비밀번호 제외, profile image api 및 api문서 생성
  azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/dto/MemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberService.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/MemberStubData.java
Labels: docs, feat, Backend

#193 Feat/main page
  azit-front/src/components/AzitCreate/AzitCreateForm.js
  azit-front/src/components/ChatList/ChatListWrap.js
  azit-front/src/components/Home/CategoryTab.js
  azit-front/src/components/Home/DateTab.js
  azit-front/src/components/Home/Null.js
  azit-front/src/components/Home/RecommendTab.js
  azit-front/src/components/Search/Defalut.js
  azit-front/src/dummyData/ChatData.js
  azit-front/src/pages/Search.js
Labels: feat, Frontend

#195 [feat] 비밀번호 찾기 페이지 UI 수정 및 비밀번호 변경 페이지 기능 구현
  azit-front/package-lock.json
  azit-front/src/pages/FindPassword.js
  azit-front/src/pages/Login.js
  azit-front/src/pages/Signup.js
  azit-front/src/pages/SignupAdditional.js
  azit-front/src/pages/UserResetPassword.js
Labels: feat, Frontend

#192 [club] 회원 추천 카테고리 조회, 아지트 신고기능 구현
  azit-back/src/docs/asciidoc/index.adoc
  azit-back/src/main/java/com/codestates/azitserver/domain/club/controller/ClubController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/controller/ClubReportController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubReportDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/entity/Club.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/mapper/ClubMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/mapper/ClubReportMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/repository/ClubReportRepository.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/repository/ClubRepository.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubReportService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/common/Report.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/dto/MemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ExceptionCode.java
  azit-back/src/main/resources/data.sql
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubMemberControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubReportControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/descriptor/ClubFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/descriptor/ClubMemberFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/descriptor/ClubReportFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/helper/ClubControllerTestHelper.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/helper/ClubMemberControllerTestHelper.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/ClubReportStubData.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/ClubStubData.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/MemberStubData.java
Labels: feat, Backend

#197 fix: 아지트 수정 페이지 마크업 수정
  azit-front/src/components/AzitEdit/AzitEditForm.js
Labels: fix, Frontend

#198 [deploy] aws 파라미터 스토어 등록을 위한 작업
  azit-back/build.gradle
  azit-back/scripts/deploy.sh
  azit-back/src/main/java/com/codestates/azitserver/TestCommandLineRunner.java
  azit-back/src/main/resources/application-aws.yml
  azit-back/src/main/resources/data.sql
Labels: deploy, Backend

#200 fix: AzitDetail 과 AzitPreview 마크업 수정
  azit-front/src/components/AzitCreate/AzitCreateForm.js
  azit-front/src/components/AzitEdit/AzitEditForm.js
  azit-front/src/pages/AzitDetail.js
  azit-front/src/pages/AzitPreview.js
Labels: fix, Frontend

#201 [hotfix/auth] 로그인 response 수정
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/controller/AuthController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/dto/AuthDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/filter/JwtAuthenticationFilter.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/handler/OAuthSuccessHandler.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/service/AuthService.java
  azit-back/src/test/java/com/codestates/azitserver/domain/auth/authControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/auth/authLoginTest.java
Labels: refact, Backend

#208 [Fix/club] 비회원 추천 아지트, 클럽 호스트, 신청 회원의 프로필 정보 추가
  azit-back/src/main/java/com/codestates/azitserver/TestCommandLineRunner.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/controller/ClubController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/mapper/ClubMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/fileInfo/dto/FileInfoDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/fileInfo/mapper/FileInfoMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/dto/MemberDto.java
  azit-back/src/main/resources/data.sql
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/descriptor/ClubFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/descriptor/ClubReportFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/ClubStubData.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/FileInfoStubData.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/MemberStubData.java
Labels: fix, Backend

#209 [feat] 비밀번호 인증 기능 및 로그인 시 memberId 로컬 저장 기능 구현
  azit-front/src/App.js
  azit-front/src/pages/Login.js
  azit-front/src/pages/UserPageSetting.js
  azit-front/src/pages/UserVerifyPassword.js
Labels: feat, Frontend

#213 [feat] 아지트 페이지에서 유저 페이지로 링크 연결
  azit-front/src/App.js
  azit-front/src/components/AzitEdit/AzitEditForm.js
  azit-front/src/pages/AzitDetail.js
Labels: feat, Frontend

#217 [hotfix] 예외처리, 아지트 배너 이미지 경로 설정 문제
  azit-back/src/main/java/com/codestates/azitserver/domain/fileInfo/service/StorageService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/fileInfo/service/StorageServiceAwsS3.java
  azit-back/src/main/java/com/codestates/azitserver/domain/fileInfo/service/StorageServiceLocal.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/StorageException.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/advice/GlobalExceptionAdvice.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ExceptionCode.java
Labels: fix, Backend

#216 fix: 링크 연결 수정
  azit-front/src/App.js
  azit-front/src/components/AzitDetail/AzitDetailHeader.js
  azit-front/src/components/AzitEdit/AzitEditForm.js
  azit-front/src/pages/AzitDetail.js
  azit-front/src/pages/AzitSetting.js
Labels: fix, Frontend

#220 [feat] 비밀번호 변경 기능 구현 완료 및 회원 가입 기능 부분 구현
  azit-front/src/dummyData/SignupYear.js
  azit-front/src/pages/Signup.js
  azit-front/src/pages/SignupAdditional.js
  azit-front/src/pages/UserResetPassword.js
  azit-front/src/pages/UserVerifyPassword.js
Labels: feat, Frontend

#233 [feat] 아지트 수정 기능 구현
  azit-front/src/components/AzitEdit/AzitEditForm.js
  azit-front/src/pages/AzitEdit.js
Labels: feat, Frontend

#226 [Feat] 유저페이지 기능 구현
  azit-front/src/App.js
  azit-front/src/components/MyPage/Category.js
  azit-front/src/components/MyPage/Profile.js
  azit-front/src/components/MyPage/UserPageHeader.js
  azit-front/src/pages/UserPage.js
  azit-front/src/pages/UserProfileEdit.js
Labels: feat, Frontend

#237 [Deploy] Production server 배포 준비
  .github/workflows/gradle-server-deploy.yml
  .github/workflows/gradle-server-test.yml
  azit-back/build.gradle
  azit-back/scripts/deploy.sh
  azit-back/src/main/java/com/codestates/azitserver/domain/club/entity/Club.java
  azit-back/src/main/java/com/codestates/azitserver/domain/common/Auditable.java
  azit-back/src/main/java/com/codestates/azitserver/domain/fileInfo/service/StorageServiceLocal.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/Member.java
  azit-back/src/main/resources/application-server.yml
  azit-back/src/main/resources/data.sql
Labels: deploy, Backend

#239 Deploy/server
  azit-back/scripts/deploy.sh
Labels: deploy, Backend

#238 fix: 수정기능 중 참가비 데이터 보낼 때 오류 수정
  azit-front/src/components/AzitEdit/AzitEditForm.js
  azit-front/src/redux/azitSlice.js
  azit-front/src/redux/store.js
Labels: fix, Frontend

#244 [feat] 회원 가입 기능 구현 완료 및 LogoutRequestModal UI 수정
  azit-front/src/components/Logout/LogoutRequestModal.js
Labels: feat, Frontend

#251 Feat/azit review
  azit-front/package.json
  azit-front/src/components/MyPage/Profile.js
  azit-front/src/components/common/AzitList.js
  azit-front/src/dummyData/ClubData.js
  azit-front/src/pages/Search.js
Labels: fix, Frontend

#249 [Feat] 팔로우 확인페이지 수정
  azit-front/src/components/FollowCheck/DataList.js
  azit-front/src/components/FollowCheck/FollowData.js
Labels: fix, Frontend

#252 fix:회원가입 관심사 선택 시 버튼 활성화, 마이페이지 초입시 데이터 get, 아지트 상세페이지 헤더 패딩조절, 신고페이지…
  azit-front/src/components/AzitDetail/AzitDetailHeader.js
  azit-front/src/components/common/AzitList.js
  azit-front/src/pages/AzitReport.js
  azit-front/src/pages/SignupAdditional.js
  azit-front/src/pages/UserProfileEdit.js
Labels: fix, Frontend

#253 [fix] 비밀번호 유효성 검사 수정
  azit-front/src/pages/Signup.js
  azit-front/src/pages/UserResetPassword.js
  azit-front/src/pages/UserVerifyPassword.js
Labels: fix, Frontend

#254 [hotfix/auth] 로그인 응답값 수정
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/dto/AuthDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/filter/JwtAuthenticationFilter.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/handler/OAuthSuccessHandler.java
  azit-back/src/test/java/com/codestates/azitserver/domain/auth/authLoginTest.java
Labels: Backend

#269 [auth] 비밀번호 찾기 기능 구현
  azit-back/build.gradle
  azit-back/src/docs/asciidoc/index.adoc
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/controller/AuthController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/dto/AuthDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/dto/response/AuthResponseDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/entity/AuthNumber.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/filter/JwtAuthenticationFilter.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/handler/OAuthSuccessHandler.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/repository/AuthNumberRepository.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/service/AuthService.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/MailConfig.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ExceptionCode.java
  azit-back/src/main/resources/application.yml
  azit-back/src/test/java/com/codestates/azitserver/domain/auth/authControllerTest.java
Labels: docs, feat, test, Backend

#270 [Fix] 오후 통합테스트 하면서 발견한 에러 수정
  azit-back/src/main/java/com/codestates/azitserver/domain/club/controller/ClubMemberController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubMemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubReportDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/fileInfo/service/StorageServiceAwsS3.java
  azit-back/src/main/java/com/codestates/azitserver/global/validator/EnumValue.java
  azit-back/src/main/java/com/codestates/azitserver/global/validator/EnumValueValidator.java
  azit-back/src/main/resources/data.sql
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/ClubMemberStubData.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/ClubReportStubData.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/ClubStubData.java
Labels: fix, Backend

#255 [Feat] 유저페이지 기능 구현
  azit-front/src/components/MyPage/UserPageHeader.js
  azit-front/src/pages/UserPage.js
  azit-front/src/pages/UserProfileEdit.js
Labels: fix, Frontend

#272 fix: 날짜 제한, 멤버 제한,아지트 수정page 뒤로가기 네비게이션 수정
  azit-front/src/components/AzitCreate/AzitCreateForm.js
  azit-front/src/components/AzitEdit/AzitEditForm.js
  azit-front/src/pages/AzitCreate.js
  azit-front/src/pages/AzitDetail.js
  azit-front/src/pages/AzitPreview.js
  azit-front/src/util/azitPreviewDateConvert.js
Labels: fix, Frontend

#273 [feat] 회원가입 이미지 파일 종류 제한 수정 및 로그인 시 로컬 저장 데이터 수정
  azit-front/src/pages/Login.js
  azit-front/src/pages/SignupAdditional.js
Labels: fix, Frontend

#275 Feat/azit review
  azit-front/src/App.js
  azit-front/src/components/common/RequireAuth.js
  azit-front/src/pages/Home.js
  azit-front/src/pages/Login.js
Labels: feat, Frontend

#277 [feat] 아지트 미리보기 페이지 호스트 이미지 반영
  azit-front/src/components/AzitSetting/AzitDeleteModal.js
  azit-front/src/pages/AzitPreview.js
  azit-front/src/pages/AzitSetting.js
Labels: fix, Frontend

#278 fix: 아지트 수정 멤버 신청 상태에 따라 수정제한 항목 추가
  azit-front/src/components/AzitEdit/AzitEditForm.js
Labels: fix, Frontend

#274 [member][Hotfix] 닉네임, 이메일 중복체크만 해주는 api, report기능 일부추가
  azit-back/src/docs/asciidoc/index.adoc
  azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberReportController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/dto/MemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/dto/MemberReportDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/Member.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/MemberMemberReport.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/MemberReport.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/mapper/MemberReportMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/repository/MemberReportRepository.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberMemberReportService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberReportService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/report/entity/Report.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ExceptionCode.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberFieldDescriptor.java
Labels: docs, feat, Backend

#281 [feat] 아지트 삭제 기능 구현
  azit-front/src/pages/AzitSetting.js
Labels: feat, Frontend

#283 [feat]아지트 상세 페이지에서 아지트 참가 신청 페이지로 연결
  azit-front/src/App.js
  azit-front/src/components/AzitCreate/AzitCreateForm.js
  azit-front/src/pages/AzitDetail.js
  azit-front/src/pages/AzitJoin.js
Labels: feat, Frontend

#284 [Review] 리뷰 CRUD 기능 구현
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/review/controller/ReviewController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/review/dto/ReviewDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/review/entity/Review.java
  azit-back/src/main/java/com/codestates/azitserver/domain/review/mapper/ReviewMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/review/repository/ReviewRepository.java
  azit-back/src/main/java/com/codestates/azitserver/domain/review/service/ReviewService.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ExceptionCode.java
Labels: feat, Backend

#285 [Review,], [Club] 참여자 리뷰 테스트 코드 작성, 아지트 부분 리팩토링
  azit-back/src/docs/asciidoc/index.adoc
  azit-back/src/main/java/com/codestates/azitserver/domain/club/controller/ClubController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/controller/ClubMemberController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/repository/ClubMemberRepository.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/repository/ClubRepository.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubMemberService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/review/dto/ReviewDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/review/mapper/ReviewMapper.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubMemberControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/descriptor/ClubMemberFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/review/controller/ReviewControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/review/descriptor/ReviewFieldsDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/review/helper/ReviewControllerTestHelper.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/ClubStubData.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/ReviewStubData.java
  azit-back/src/test/java/com/codestates/azitserver/global/utils/ControllerTestHelper.java
Labels: fix, feat, refact, test, Backend

#289 [feat] 아지트 참가신청 기능 구현
  azit-front/src/pages/AzitJoin.js
Labels: feat, Frontend

#288 [Feat] 멤버신고하기 기능 구현
  azit-front/src/components/MyPage/UserPageHeader.js
  azit-front/src/dummyData/UserReportData.js
  azit-front/src/pages/AzitDetail.js
  azit-front/src/pages/Home.js
  azit-front/src/pages/UserPage.js
  azit-front/src/pages/UserProfileEdit.js
  azit-front/src/pages/UserReport.js
  azit-front/src/redux/store.js
Labels: feat, Frontend

#291 [feat] 아지트 신청/참가 멤버 조회 기능 구현
  azit-front/src/App.js
  azit-front/src/components/AzitMember/Member.js
  azit-front/src/components/AzitMember/MemberList.js
  azit-front/src/components/AzitMember/WaitingMember.js
  azit-front/src/pages/AzitMember.js
  azit-front/src/pages/AzitSetting.js
Labels: feat, Frontend

#293 [feat] 비밀번호 찾기 기능 구현
  azit-front/src/pages/FindPassword.js
Labels: feat, Frontend

#296 [feat] 회원 탈퇴 기능 구현
  azit-front/src/App.js
  azit-front/src/pages/FindPassword.js
  azit-front/src/pages/UserPageSetting.js
  azit-front/src/pages/UserWithdrawl.js
Labels: feat, Frontend

#299 feat: 아지트 신청 수락/거절 및 강퇴 기능 구현
  azit-front/src/components/AzitEdit/AzitEditForm.js
  azit-front/src/components/AzitMember/Member.js
  azit-front/src/components/AzitMember/MemberList.js
  azit-front/src/pages/AzitDetail.js
Labels: feat, Frontend

#301 feat: 아지트 유저별 상태에 따른 아지트 상세 페이지 버튼 변화
  azit-front/src/pages/AzitDetail.js
Labels: feat, Frontend

#302 fix: 아지트 상세 페이지 버튼 오류 수정
  azit-front/src/pages/AzitDetail.js
Labels: fix, Frontend

#303 [auth/logout] 로그아웃 기능
  azit-back/src/docs/asciidoc/index.adoc
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/controller/AuthController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/dto/response/AuthResponseDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/filter/JwtAuthenticationFilter.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/filter/JwtVerificationFilter.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/handler/OAuthSuccessHandler.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/jwt/JwtTokenizer.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/service/AuthService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/utils/RedisUtils.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ExceptionCode.java
  azit-back/src/test/java/com/codestates/azitserver/domain/auth/authControllerTest.java
Labels: fix, docs, feat, test, Backend

#304 [member] 닉네임, 이메일 중복체크 토큰 권한 해제
  azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberReportController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/MemberMemberReport.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ExceptionCode.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberReportControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/descriptor/MemberFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/descriptor/MemberReportFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/MemberReportStubData.java
Labels: fix, Backend

#306 feat: 배너 이미지 크롭 기능 구현
  azit-front/package-lock.json
  azit-front/package.json
  azit-front/src/components/AzitCreate/AzitCreateForm.js
  azit-front/src/components/AzitCreate/ImageModal.js
  azit-front/src/pages/AzitCreate.js
  azit-front/src/pages/AzitPreview.js
Labels: feat, Frontend

#319 [feat] 소셜 로그인 기능 및 로그아웃 통신 기능 부분구현
  azit-front/package-lock.json
  azit-front/src/App.js
  azit-front/src/pages/Login.js
  azit-front/src/pages/OauthGoogle.js
  azit-front/src/pages/SignupAdditional.js
  azit-front/src/pages/UserPageSetting.js
  azit-front/src/pages/UserVerifyPassword.js
  azit-front/src/util/axios.js
  azit-front/src/util/oauthGoogle.js
Labels: feat, Frontend

#318 [member] 중복체크 권한해제 다시
  azit-back/src/docs/asciidoc/index.adoc
  azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberReportController.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberReportControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/ClubStubData.java
Labels: fix, Backend

#320 [Fix/review, clubMember] 리뷰 도메인 관련 수정사항 업데이트
  azit-back/src/docs/asciidoc/index.adoc
  azit-back/src/main/java/com/codestates/azitserver/domain/club/controller/ClubController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/controller/ClubMemberController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/entity/Club.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubMemberService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/dto/MemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/review/controller/ReviewController.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/ClubMemberControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/descriptor/ClubMemberFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/review/controller/ReviewControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/review/descriptor/ReviewFieldsDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/MemberStubData.java
  azit-back/src/test/java/com/codestates/azitserver/global/utils/ControllerTestHelper.java
Labels: fix, Backend

#323 fix: 강퇴 기능 오류 수정
  azit-front/src/components/AzitMember/MemberList.js
Labels: fix, Frontend

#324 feat: 로그아웃 통신 기능 구현 완료
  azit-front/src/pages/UserPageSetting.js
Labels: feat, Frontend

#325 [member] 닉,이메일 중복검사 재수정
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubMemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/mapper/ClubMemberMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/repository/ClubMemberRepository.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubMemberService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/dto/MemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/Member.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberControllerTest.java
Labels: fix, Backend

#329 fix: 아지트 상세 페이지 버튼 오류 수정
  azit-front/src/pages/AzitDetail.js
  azit-front/src/pages/AzitJoin.js
Labels: fix, Frontend

#328 [auth] 토큰 재발급 수정
  azit-back/src/docs/asciidoc/index.adoc
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/controller/AuthController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/dto/AuthDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/service/AuthService.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/test/java/com/codestates/azitserver/domain/auth/authControllerTest.java
Labels: fix, Backend

#331 [feat] 닉네임 / 이메일 중복검사 기능 구현 및 토큰 재발급 기능 부분구현
  azit-front/src/pages/Login.js
  azit-front/src/pages/Signup.js
  azit-front/src/pages/SignupAdditional.js
  azit-front/src/util/axios.js
Labels: feat, Frontend

#335 [Member/Follow] 팔로우 기능 구현(일부)
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/controller/FollowController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/dto/FollowDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/entity/Follow.java
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/mapper/FollowMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/repository/FollowRepository.java
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/service/FollowService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/Member.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ExceptionCode.java
Labels: feat, Backend

#336 [auth/hotfix] 토큰 재발급 방식 변경
  azit-back/src/docs/asciidoc/index.adoc
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/controller/AuthController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/dto/AuthDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/service/AuthService.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/main/resources/application.yml
  azit-back/src/test/java/com/codestates/azitserver/domain/auth/authControllerTest.java
Labels: fix, docs, test, Backend, style

#339 fix: 아지트 강퇴 기능 axios로 수정
  azit-front/src/components/AzitMember/MemberList.js
Labels: fix, Frontend

#340 fix: 아지트 신청 멤버 수락,거절, 강퇴시 바로 반영
  azit-front/src/components/AzitMember/MemberList.js
Labels: fix, Frontend

#342 [Member/follow] 팔로우 도메인 기능 구현
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/controller/FollowController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/dto/FollowDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/entity/Follow.java
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/mapper/FollowMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/repository/FollowRepository.java
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/service/FollowService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/dto/MemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/mapper/MemberMapper.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
Labels: feat, Backend

#344 [member] 활동내역 기능 구현
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubMemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/mapper/ClubMemberMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubMemberService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/Member.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/review/repository/ReviewRepository.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/main/resources/data.sql
Labels: feat, Backend

#347 fix: 아지트 멤버 렌더링 시 오류 수정
  azit-front/src/components/AzitMember/Member.js
  azit-front/src/components/AzitMember/WaitingMember.js
Labels: fix, Frontend

#351 [Follow/test] 팔로우 도메인 테스트 코드 작성
  azit-back/src/docs/asciidoc/index.adoc
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/controller/FollowController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/dto/FollowDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/entity/Follow.java
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/mapper/FollowMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/repository/FollowRepository.java
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/service/FollowService.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/test/java/com/codestates/azitserver/domain/follow/controller/FollowControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/follow/descrpitor/FollowFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/follow/helper/FollowControllerTestHelper.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/descriptor/MemberFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/review/controller/ReviewControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/FollowStubData.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/MemberStubData.java
  azit-back/src/test/java/com/codestates/azitserver/global/utils/ControllerTestHelper.java
Labels: test, Backend

#352 fix: 아지트 배너 이미지 크롭 모달 수정
  azit-front/src/components/AzitCreate/ImageModal.js
Labels: fix, Frontend

#356 [feat] 구글 소셜 로그인 및 토큰 재발급 기능 부분 구현
  azit-front/src/pages/Login.js
  azit-front/src/pages/OauthGoogle.js
  azit-front/src/pages/UserPageSetting.js
  azit-front/src/util/axios.js
  azit-front/src/util/useAxios.js
Labels: feat, Frontend

#362 [member][club] 활동내역 조회에 아지트 정보, 참여자 정보 포함
  azit-back/src/docs/asciidoc/index.adoc
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubMemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/mapper/ClubMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubMemberService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/dto/MemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/mapper/MemberMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberService.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/descriptor/MemberFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/ClubMemberStubData.java
Labels: feat, Backend

#369 [member] 회원가입 이미지 결합 로직 수정
  azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberService.java
Labels: fix, Backend

#374 [Fix/deploy] 3차 배포 서버 수정 반영
  azit-back/scripts/deploy.sh
  azit-back/scripts/deploy_main.sh
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubMemberService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/review/controller/ReviewController.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ExceptionCode.java
  azit-back/src/main/resources/application-local.yml
  azit-back/src/main/resources/application-server.yml
  azit-back/src/main/resources/data.sql
Labels: fix, deploy, Backend

#372 fix: 아지트 생성시 제한 걸기 추가
  azit-front/src/components/AzitCreate/AzitCreateForm.js
  azit-front/src/components/AzitCreate/ImageModal.js
  azit-front/src/pages/AzitCreate.js
Labels: fix, Frontend

#373 [member] 3차배포 버그 수정
  azit-back/src/main/java/com/codestates/azitserver/domain/category/service/CategoryService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberReportController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/dto/MemberReportDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberService.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ExceptionCode.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberReportControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/MemberReportStubData.java
Labels: fix, Backend

#378 fix: 아지트 상세페이지 호스트 이미지 div로 수정
  azit-front/src/pages/AzitDetail.js
Labels: fix, Frontend

#400 [member] 이메일, 닉네임 중복체크 변경
  azit-back/src/docs/asciidoc/index.adoc
  azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/dto/MemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberService.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ExceptionCode.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberControllerTest.java
Labels: fix, Backend

#398 [fix] 회원 가입 중복 검사 및 관련 버튼 이벤트 수정
  azit-front/src/pages/Signup.js
Labels: fix, Frontend

#401 [auth/hotfix] 토큰 만료시간 변경
  azit-back/src/main/resources/application.yml
Labels: fix, docs, Backend

#404 [member] 중복체크 uri 수정, 그에 따른 security config 수정
  azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/dto/MemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberControllerTest.java
Labels: fix, Backend

#405 [fix] 회원가입 중복검사 통신 코드 수정 및 통신 기능 오류 수정 완료
  azit-front/src/pages/Signup.js
Labels: fix, Frontend

#406 fix: 아지트 멤버리스트 이미지 div로 수정
  azit-front/src/components/AzitMember/MemberList.js
Labels: fix, Frontend

#409 [member, report] 회원 신고 오류(controller 업데이트 미반영 문제) 해결
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/entity/Follow.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberReportController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/Member.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberService.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
Labels: fix, Backend

#412 [auth/fix] 토큰만료 복구, 리포
  azit-back/src/main/java/com/codestates/azitserver/domain/auth/handler/OAuthSuccessHandler.java
  azit-back/src/main/java/com/codestates/azitserver/domain/category/controller/CategoryController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/category/repository/CategorySmallRepository.java
  azit-back/src/main/java/com/codestates/azitserver/domain/category/service/CategoryService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/controller/ClubMemberController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubMemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/mapper/ClubMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/mapper/ClubMemberMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubMemberService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/common/CustomBeanUtils.java
  azit-back/src/main/java/com/codestates/azitserver/domain/common/Report.java
  azit-back/src/main/java/com/codestates/azitserver/domain/fileInfo/service/StorageServiceLocal.java
  azit-back/src/main/java/com/codestates/azitserver/domain/follow/service/FollowService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberReportController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/dto/MemberDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/dto/MemberReportDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/Member.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/MemberCategory.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/MemberReport.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/mapper/MemberMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/mapper/MemberReportMapper.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/repository/MemberReportRepository.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberCategoryService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberReportService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberService.java
  azit-back/src/main/java/com/codestates/azitserver/domain/review/controller/ReviewController.java
  azit-back/src/main/java/com/codestates/azitserver/domain/review/dto/ReviewDto.java
  azit-back/src/main/java/com/codestates/azitserver/domain/review/service/ReviewService.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/MailConfig.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/P6SpySqlFormatter.java
  azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/advice/GlobalExceptionAdvice.java
  azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ExceptionCode.java
  azit-back/src/main/resources/application.yml
  azit-back/src/test/java/com/codestates/azitserver/domain/auth/authLoginTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/club/controller/helper/ClubMemberControllerTestHelper.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberReportControllerTest.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/descriptor/MemberFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/descriptor/MemberReportFieldDescriptor.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/ClubMemberStubData.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/FileInfoStubData.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/MemberReportStubData.java
  azit-back/src/test/java/com/codestates/azitserver/domain/stub/MemberStubData.java
Labels: refact, Backend

#414 [fix] 구글 로그인 버튼 삭제
  azit-front/src/pages/Login.js
Labels: fix, Frontend
